# TCL File Generated by Component Editor 15.0
# Mon Oct 01 01:11:43 BRT 2018
# DO NOT MODIFY


# 
# KeccakAccel "KeccakAccel" v1.0
#  2018.10.01.01:11:43
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module KeccakAccel
# 
set_module_property DESCRIPTION ""
set_module_property NAME KeccakAccel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME KeccakAccel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkKeccakAccel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkKeccakAccel.v VERILOG PATH mkKeccakAccel.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender ins irq_n Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RST_N reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave address address Input 12
add_interface_port avalon_slave writedata writedata Input 64
add_interface_port avalon_slave readdata readdata Output 64
add_interface_port avalon_slave waitrequest waitrequest Output 1
add_interface_port avalon_slave readdatavalid readdatavalid Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dma_avalon_master
# 
add_interface dma_avalon_master avalon start
set_interface_property dma_avalon_master addressUnits SYMBOLS
set_interface_property dma_avalon_master associatedClock clock
set_interface_property dma_avalon_master associatedReset reset
set_interface_property dma_avalon_master bitsPerSymbol 8
set_interface_property dma_avalon_master burstOnBurstBoundariesOnly false
set_interface_property dma_avalon_master burstcountUnits WORDS
set_interface_property dma_avalon_master doStreamReads false
set_interface_property dma_avalon_master doStreamWrites false
set_interface_property dma_avalon_master holdTime 0
set_interface_property dma_avalon_master linewrapBursts false
set_interface_property dma_avalon_master maximumPendingReadTransactions 16
set_interface_property dma_avalon_master maximumPendingWriteTransactions 0
set_interface_property dma_avalon_master readLatency 0
set_interface_property dma_avalon_master readWaitTime 1
set_interface_property dma_avalon_master setupTime 0
set_interface_property dma_avalon_master timingUnits Cycles
set_interface_property dma_avalon_master writeWaitTime 0
set_interface_property dma_avalon_master ENABLED true
set_interface_property dma_avalon_master EXPORT_OF ""
set_interface_property dma_avalon_master PORT_NAME_MAP ""
set_interface_property dma_avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property dma_avalon_master SVD_ADDRESS_GROUP ""

add_interface_port dma_avalon_master dma_read read Output 1
add_interface_port dma_avalon_master dma_write write Output 1
add_interface_port dma_avalon_master dma_address address Output 64
add_interface_port dma_avalon_master dma_writedata writedata Output 64
add_interface_port dma_avalon_master dma_readdata readdata Input 64
add_interface_port dma_avalon_master dma_waitrequest waitrequest Input 1
add_interface_port dma_avalon_master dma_readdatavalid readdatavalid Input 1

